merge actions into one

diff --git a/.github/workflows/lint_and_test_cov.yml b/.github/workflows/lint_and_test_cov.yml
--- a/.github/workflows/lint_and_test_cov.yml
+++ b/.github/workflows/lint_and_test_cov.yml
@@ -1,29 +1,45 @@
-name: Update Coverage on Readme
+name: Lint and Test Cov
+
 on:
-  workflow_run:
-    workflows: [Lint]
+  pull_request:
     types:
-      - completed
+      - opened
+      - synchronize
 
 jobs:
-  update-coverage-on-readme:
+  lint_and_update_pr:
+    name: Lint and Update PR
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v3
+      - name: Check out Git repository
+        uses: actions/checkout@v3
         with:
-          persist-credentials: true # Make sure to use a token with push access
-          fetch-depth: 0 # Necessary for a comprehensive history
           ref: ${{ github.head_ref }} # Checkout the PR branch
-          token: ${{ secrets.GITHUB_TOKEN }} # Use a token with push access
+          token: ${{ secrets.GITHUB_TOKEN }} # Ensure you have push access
 
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: "3.9"
 
-      - name: Install dependencies
+      - name: Install Python dependencies
         run: |
+          pip install black
           pip install -r requirements.txt
+
+      - name: Auto-format code with black and commit changes
+        run: |
+          black . || true  # Format code, but don't fail the job if formatting made changes
+          if [ -n "$(git status --porcelain)" ]; then  # Check if there are changes
+            git config user.name 'github-actions[bot]'
+            git config user.email 'github-actions[bot]@users.noreply.github.com'
+            git add .
+            git commit -m "Apply auto-formatting with black"
+            git push
+          else
+            echo "No changes made by black."
+          fi
 
       - name: Run pytest and generate report
         run: |
@@ -39,9 +55,6 @@ jobs:
       - name: Update Readme with Coverage
         run: |
           sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
-
-          # Pull latest changes from the remote repository
-          git pull origin HEAD
 
           # Check if there are any changes
           if git diff --quiet README.md; then
